/**
 * Single FAQ list for /placements/ - rendered by page.tsx, marked up by layout.tsx (see app/erode/faqs.ts).
 */
import type { FaqItem } from '@/lib/faq';
import collegeFacts from '@/data/collegeFacts';

export const faqs: FaqItem[] = [
  { q: 'What is the placement rate at JKKN Dental College?', a: `For the ${collegeFacts.placementBds.batch} batch, ${collegeFacts.placementBds.placed} of ${collegeFacts.placementBds.graduated} BDS graduates were placed and ${collegeFacts.placementBds.higherStudies} went on to higher studies - ${collegeFacts.placementOutcomeRate}% placed or in higher studies, with a median salary of Rs ${(collegeFacts.placementBds.medianSalary/100000).toFixed(1)} lakh. All ${collegeFacts.placementMds.graduated} MDS graduates were placed, median Rs ${(collegeFacts.placementMds.medianSalary/100000).toFixed(1)} lakh. These are the figures JKKN filed with the Ministry of Education in its NIRF 2026 submission. The Career Development Centre (CDC) provides resume building, interview preparation and recruiter connections.` },
  { q: 'Which companies hire from JKKN Dental College?', a: 'Top recruiters include Apollo Dental, Clove Dental, Sabka Dentist, MyDentist, Apollo Hospitals, Fortis Healthcare, Manipal Hospitals, and government PHCs & district hospitals. International recruiters include NHS UK, Cleveland Clinic Abu Dhabi, and Saudi MOH.' },
  { q: 'What is the salary after BDS from JKKN Dental College?', a: 'For the 2024-25 BDS batch, the JKKN NIRF 2026 filing to the Ministry of Education records a median salary of Rs 3,60,000. Of 99 graduates, 75 were placed and 18 went on to higher studies.' },
  { q: 'Does JKKN Dental College offer international placements?', a: 'Yes, JKKN Dental College alumni work internationally at NHS UK, Cleveland Clinic Abu Dhabi, Saudi Ministry of Health, and dental clinics in Singapore. The CDC supports international licensing exam preparation and placement assistance.' },
  { q: 'What career options are available after BDS?', a: 'After BDS from JKKN, graduates can pursue private practice, hospital dentistry, higher studies (MDS), international opportunities, dental research, or public health dentistry. The CDC provides guidance for all career pathways.' },
  { q: 'How does the JKKN Dental Placement Cell work?', a: `The CDC operates a structured 5-step process: Registration & Profile Building, Resume Workshop & Skill Development, Company Connect & Campus Drives, Interview Preparation & Mock Sessions, and Offer Facilitation & Joining Support. With ${collegeFacts.partnerships}+ recruiting partners, the CDC ensures comprehensive placement support.` },
  { q: 'What is the highest package from JKKN Dental College?', a: 'JKKN does not publish a highest-package figure. The sourced number is the median: Rs 3,60,000 for the 2024-25 BDS batch and Rs 6,00,000 for MDS, per the JKKN NIRF 2026 filing to the Ministry of Education.' },
  { q: 'Can JKKN Dental learners get government jobs?', a: 'Yes, many JKKN Dental alumni serve in government Primary Health Centres (PHCs), district hospitals, and dental departments across Tamil Nadu. The college provides guidance for TNPSC and other government dental recruitment exams.' },
  { q: 'How many alumni does JKKN Dental College have?', a: `JKKN Dental College has a strong alumni network of ${collegeFacts.alumniCount.toLocaleString()}+ graduates spread across India and internationally. Alumni work in leading hospitals, corporate dental chains, government services, and private practice.` },
  { q: 'Is JKKN Dental College good for higher studies after BDS?', a: `Yes, JKKN Dental College has a strong track record of learners clearing NEET MDS and pursuing postgraduate specialisations. The college offers MDS in ${collegeFacts.mdsSpecialisations} specialisations and provides dedicated coaching and mentoring for competitive exams.` },
  { q: 'Does JKKN have placement for MDS learners?', a: `Yes, MDS graduates from JKKN receive dedicated placement support. With advanced clinical training across ${collegeFacts.mdsSpecialisations} specialisations and ${collegeFacts.publications}+ senior learner publications, MDS graduates are placed in teaching institutions, specialty hospitals, and research organisations.` },
];
